language: node_js
node_js:
  - "5"

addons:
  firefox: "latest"

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g gulp

install:
  - npm install
  - npm run typings install

script: gulp
sudo: false
